site: vtky
url: https://vtky.github.io
title: Sidey
description: vtky's github.io
twitter:
  username: vincent_tky
  card: summary
  creator: vincent_tky
author:
  twitter: vincent_tky
  name: vtky
  avatar:
  email: #youremail
  url: vtky.github.io
permalink: pretty

baseurl: ""

highlighter: none

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug

markdown: kramdown

kramdown:
  # auto_id_prefix: 
  auto_id_stripping: false
  auto_ids: true
  entity_output: as_char
  # footnote_backlink: &#8617;
  footnote_backlink_inline: false
  footnote_nr: 1
  hard_wrap: false
  header_offset: 0
  html_to_native: false
  input: GFM
  line_width: 72
  parse_block_html: false
  parse_span_html: true
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  syntax_highlighter: rouge
  show_warnings: false


defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"